"""Add Zion v50 models

Revision ID: 4c126f914711
Revises: 
Create Date: 2026-04-11 11:15:26.847989

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4c126f914711'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caja',
    sa.Column('caj_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caj_fecha', sa.Date(), nullable=True),
    sa.Column('caj_usuario', sa.String(length=50), nullable=False),
    sa.Column('caj_ventasefe', sa.Float(), nullable=True),
    sa.Column('caj_ventasche', sa.Float(), nullable=True),
    sa.Column('caj_cobrosdeu', sa.Float(), nullable=True),
    sa.Column('caj_adelanto', sa.Float(), nullable=True),
    sa.Column('caj_otros_ing', sa.Float(), nullable=True),
    sa.Column('caj_compras', sa.Float(), nullable=True),
    sa.Column('caj_pagoprov', sa.Float(), nullable=True),
    sa.Column('caj_gastos', sa.Float(), nullable=True),
    sa.Column('caj_devoluc', sa.Float(), nullable=True),
    sa.Column('caj_otros_egr', sa.Float(), nullable=True),
    sa.Column('caj_saldoinicial', sa.Float(), nullable=True),
    sa.Column('caj_totalingre', sa.Float(), nullable=True),
    sa.Column('caj_totalegre', sa.Float(), nullable=True),
    sa.Column('caj_saldofinal', sa.Float(), nullable=True),
    sa.Column('caj_cerrada', sa.Boolean(), nullable=True),
    sa.Column('caj_fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('caj_observacion', sa.String(length=255), nullable=True),
    sa.Column('caj_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('caj_nro'),
    sa.UniqueConstraint('caj_fecha')
    )
    op.create_index(op.f('ix_caja_caj_nro'), 'caja', ['caj_nro'], unique=False)
    op.create_table('cheque',
    sa.Column('che_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('che_numero', sa.String(length=50), nullable=False),
    sa.Column('che_fecha', sa.Date(), nullable=True),
    sa.Column('che_fecha_venc', sa.Date(), nullable=False),
    sa.Column('che_librador', sa.String(length=100), nullable=True),
    sa.Column('che_banco', sa.String(length=100), nullable=True),
    sa.Column('che_cuenta', sa.String(length=50), nullable=True),
    sa.Column('che_monto', sa.Float(), nullable=False),
    sa.Column('che_tipo', sa.String(length=20), nullable=True),
    sa.Column('che_estado', sa.String(length=20), nullable=True),
    sa.Column('che_conceptonro', sa.String(length=50), nullable=True),
    sa.Column('che_usuario', sa.String(length=50), nullable=True),
    sa.Column('che_fecha_deposito', sa.Date(), nullable=True),
    sa.Column('che_observacion', sa.String(length=255), nullable=True),
    sa.Column('che_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('che_nro'),
    sa.UniqueConstraint('che_numero')
    )
    op.create_index(op.f('ix_cheque_che_nro'), 'cheque', ['che_nro'], unique=False)
    op.create_table('gasto',
    sa.Column('gas_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gas_fecha', sa.Date(), nullable=True),
    sa.Column('gas_concepto', sa.String(length=100), nullable=False),
    sa.Column('gas_monto', sa.Float(), nullable=False),
    sa.Column('gas_categoria', sa.String(length=50), nullable=True),
    sa.Column('gas_usuario', sa.String(length=50), nullable=True),
    sa.Column('gas_comprobante', sa.String(length=50), nullable=True),
    sa.Column('gas_observacion', sa.String(length=255), nullable=True),
    sa.Column('gas_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('gas_nro')
    )
    op.create_index(op.f('ix_gasto_gas_nro'), 'gasto', ['gas_nro'], unique=False)
    op.create_table('motivo',
    sa.Column('mot_cod', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mot_descri', sa.String(length=100), nullable=False),
    sa.Column('mot_tipo', sa.String(length=20), nullable=False),
    sa.Column('mot_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mot_cod')
    )
    op.create_index(op.f('ix_motivo_mot_cod'), 'motivo', ['mot_cod'], unique=False)
    op.create_table('movimiento_caja',
    sa.Column('mov_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mov_fecha', sa.DateTime(), nullable=True),
    sa.Column('mov_caja', sa.Integer(), nullable=False),
    sa.Column('mov_tipo', sa.String(length=20), nullable=False),
    sa.Column('mov_concepto', sa.String(length=100), nullable=False),
    sa.Column('mov_documento', sa.String(length=50), nullable=True),
    sa.Column('mov_monto', sa.Float(), nullable=False),
    sa.Column('mov_observacion', sa.String(length=255), nullable=True),
    sa.Column('mov_usuario', sa.String(length=50), nullable=True),
    sa.Column('mov_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mov_nro')
    )
    op.create_index(op.f('ix_movimiento_caja_mov_nro'), 'movimiento_caja', ['mov_nro'], unique=False)
    op.create_table('proveedor',
    sa.Column('prov_cod', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prov_ruc', sa.String(length=20), nullable=False),
    sa.Column('prov_nom', sa.String(length=255), nullable=False),
    sa.Column('prov_dir', sa.String(length=255), nullable=True),
    sa.Column('prov_tel', sa.String(length=20), nullable=True),
    sa.Column('prov_email', sa.String(length=100), nullable=True),
    sa.Column('prov_contacto', sa.String(length=100), nullable=True),
    sa.Column('prov_limite', sa.Float(), nullable=True),
    sa.Column('prov_sal', sa.Float(), nullable=True),
    sa.Column('prov_activo', sa.Boolean(), nullable=True),
    sa.Column('prov_fecha_reg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('prov_cod')
    )
    op.create_index(op.f('ix_proveedor_prov_cod'), 'proveedor', ['prov_cod'], unique=False)
    op.create_index(op.f('ix_proveedor_prov_ruc'), 'proveedor', ['prov_ruc'], unique=True)
    op.create_table('ajuste',
    sa.Column('aju_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aju_fecha', sa.DateTime(), nullable=True),
    sa.Column('aju_procod', sa.Integer(), nullable=False),
    sa.Column('aju_cant', sa.Float(), nullable=False),
    sa.Column('aju_motivo', sa.Integer(), nullable=True),
    sa.Column('aju_usuario', sa.String(length=50), nullable=True),
    sa.Column('aju_observacion', sa.String(length=255), nullable=True),
    sa.Column('aju_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aju_procod'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('aju_nro')
    )
    op.create_index(op.f('ix_ajuste_aju_nro'), 'ajuste', ['aju_nro'], unique=False)
    op.create_table('compra',
    sa.Column('com_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('com_fecha', sa.DateTime(), nullable=True),
    sa.Column('com_proveedor', sa.Integer(), nullable=False),
    sa.Column('com_total', sa.Float(), nullable=True),
    sa.Column('com_tipo', sa.Integer(), nullable=True),
    sa.Column('com_usuario', sa.String(length=50), nullable=True),
    sa.Column('com_estado', sa.String(length=20), nullable=True),
    sa.Column('com_observacion', sa.String(length=255), nullable=True),
    sa.Column('com_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['com_proveedor'], ['proveedor.prov_cod'], ),
    sa.PrimaryKeyConstraint('com_nro')
    )
    op.create_index(op.f('ix_compra_com_nro'), 'compra', ['com_nro'], unique=False)
    op.create_table('compra_item',
    sa.Column('citem_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citem_compnro', sa.Integer(), nullable=False),
    sa.Column('citem_procod', sa.Integer(), nullable=False),
    sa.Column('citem_cant', sa.Float(), nullable=False),
    sa.Column('citem_precio', sa.Float(), nullable=False),
    sa.Column('citem_subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['citem_compnro'], ['compra.com_nro'], ),
    sa.ForeignKeyConstraint(['citem_procod'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('citem_id')
    )
    op.create_index(op.f('ix_compra_item_citem_id'), 'compra_item', ['citem_id'], unique=False)
    op.create_table('cuota',
    sa.Column('cuo_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuo_factnro', sa.Integer(), nullable=False),
    sa.Column('cuo_cliente', sa.Integer(), nullable=False),
    sa.Column('cuo_numero', sa.Integer(), nullable=False),
    sa.Column('cuo_monto', sa.Float(), nullable=False),
    sa.Column('cuo_fecha_venc', sa.Date(), nullable=False),
    sa.Column('cuo_fecha_pago', sa.Date(), nullable=True),
    sa.Column('cuo_pagado', sa.Boolean(), nullable=True),
    sa.Column('cuo_observacion', sa.String(length=255), nullable=True),
    sa.Column('cuo_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cuo_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['cuo_factnro'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('cuo_nro')
    )
    op.create_index(op.f('ix_cuota_cuo_nro'), 'cuota', ['cuo_nro'], unique=False)
    op.create_table('devolucion',
    sa.Column('dev_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dev_fecha', sa.DateTime(), nullable=True),
    sa.Column('dev_facturnro', sa.Integer(), nullable=False),
    sa.Column('dev_cliente', sa.Integer(), nullable=False),
    sa.Column('dev_motivo', sa.String(length=255), nullable=False),
    sa.Column('dev_total', sa.Float(), nullable=True),
    sa.Column('dev_usuario', sa.String(length=50), nullable=True),
    sa.Column('dev_estado', sa.String(length=20), nullable=True),
    sa.Column('dev_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dev_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['dev_facturnro'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('dev_nro')
    )
    op.create_index(op.f('ix_devolucion_dev_nro'), 'devolucion', ['dev_nro'], unique=False)
    op.create_table('devolucion_item',
    sa.Column('ditem_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ditem_devnro', sa.Integer(), nullable=False),
    sa.Column('ditem_procod', sa.Integer(), nullable=False),
    sa.Column('ditem_cant', sa.Float(), nullable=False),
    sa.Column('ditem_precio', sa.Float(), nullable=False),
    sa.Column('ditem_subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ditem_devnro'], ['devolucion.dev_nro'], ),
    sa.ForeignKeyConstraint(['ditem_procod'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('ditem_id')
    )
    op.create_index(op.f('ix_devolucion_item_ditem_id'), 'devolucion_item', ['ditem_id'], unique=False)
    op.create_table('nota_credito',
    sa.Column('nc_nro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nc_fecha', sa.DateTime(), nullable=True),
    sa.Column('nc_devnro', sa.Integer(), nullable=False),
    sa.Column('nc_cliente', sa.Integer(), nullable=False),
    sa.Column('nc_monto', sa.Float(), nullable=False),
    sa.Column('nc_estado', sa.String(length=20), nullable=True),
    sa.Column('nc_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['nc_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['nc_devnro'], ['devolucion.dev_nro'], ),
    sa.PrimaryKeyConstraint('nc_nro')
    )
    op.create_index(op.f('ix_nota_credito_nc_nro'), 'nota_credito', ['nc_nro'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nota_credito_nc_nro'), table_name='nota_credito')
    op.drop_table('nota_credito')
    op.drop_index(op.f('ix_devolucion_item_ditem_id'), table_name='devolucion_item')
    op.drop_table('devolucion_item')
    op.drop_index(op.f('ix_devolucion_dev_nro'), table_name='devolucion')
    op.drop_table('devolucion')
    op.drop_index(op.f('ix_cuota_cuo_nro'), table_name='cuota')
    op.drop_table('cuota')
    op.drop_index(op.f('ix_compra_item_citem_id'), table_name='compra_item')
    op.drop_table('compra_item')
    op.drop_index(op.f('ix_compra_com_nro'), table_name='compra')
    op.drop_table('compra')
    op.drop_index(op.f('ix_ajuste_aju_nro'), table_name='ajuste')
    op.drop_table('ajuste')
    op.drop_index(op.f('ix_proveedor_prov_ruc'), table_name='proveedor')
    op.drop_index(op.f('ix_proveedor_prov_cod'), table_name='proveedor')
    op.drop_table('proveedor')
    op.drop_index(op.f('ix_movimiento_caja_mov_nro'), table_name='movimiento_caja')
    op.drop_table('movimiento_caja')
    op.drop_index(op.f('ix_motivo_mot_cod'), table_name='motivo')
    op.drop_table('motivo')
    op.drop_index(op.f('ix_gasto_gas_nro'), table_name='gasto')
    op.drop_table('gasto')
    op.drop_index(op.f('ix_cheque_che_nro'), table_name='cheque')
    op.drop_table('cheque')
    op.drop_index(op.f('ix_caja_caj_nro'), table_name='caja')
    op.drop_table('caja')
    # ### end Alembic commands ###
